[project]
name = "claire-wall"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pelican-katex>=1.8.2",
    "pelican[markdown]>=4.11.0",
    "typogrify>=2.1.0",
]

[dependency-groups]
dev = [
    "codespell>=2.4.1",
    "djlint>=1.36.4",
]
